model:
  module: models.motion_predictor.aligner.Aligner
  params:
    aligner_config:
      module: models.motion_predictor.tanet.TANet
      params:
        dim: 1024
        

    
    optimizer_config:
      module: torch.optim.AdamW
      weight_decay: 0.05
      betas: (0.9, 0.95)
      eps: 1e-8
      grad_clip: 1.0

    scheduler_config:
      module: pl_bolts.optimizers.lr_scheduler.LinearWarmupCosineAnnealingLR
      params:
        warmup_epochs: 5
        warmup_start_lr: 0.0
        eta_min: 1e-7
    
    
  
dataset:
  module: dataset.style_transfer.MotionDataManager
  params:
    data_path: /data3/leics/dataset/teeth/merged_process_nonsmoothed10x_newckpt
    index_path: "files/ours_process"
    batch_size: 16



