model:
  module: models.stage_two.stage_two_sampler.MotionTransferSampler
  params:
    transformer_config:
      module: models.stage_two.style_transformer.StyleTransformer
      params:
          z_dim: 512
          num_layers: 12
          num_heads: 8
          input_dim: 3
        

    
    optimizer_config:
      module: torch.optim.AdamW
      weight_decay: 0.05
      betas: (0.9, 0.95)
      eps: 1e-8
      grad_clip: 1.0

    scheduler_config:
      module: pl_bolts.optimizers.lr_scheduler.LinearWarmupCosineAnnealingLR
      params:
        warmup_epochs: 5
        warmup_start_lr: 0.0
        eta_min: 1e-7
    
    
  
dataset:
  module: dataset.synthetic_dataset.SyntheticDataManager
  params:
    style_path: /data3/leics/dataset/teeth/sample512_merged
    data_path: /data3/leics/dataset/teeth/sample512_merged
    index_path: "files/synthetic"
    batch_size: 16




